### ISSUE TITLE
Can't see self timer en counters of exporter

### ISSUE THREAD

**Issue by jtebbens** [rickardp/homey-prometheus-exporter#19]
In debug mode I see these messages:

MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit
    at d (/node_modules/athom-api/dist/index.js:1:1122279)
    at t.value (/node_modules/athom-api/dist/index.js:1:1125071)
    at t.value (/node_modules/athom-api/dist/index.js:1:1070714)
    at t.value (/node_modules/athom-api/dist/index.js:1:1125140)
    at t.value (/node_modules/athom-api/dist/index.js:1:1125371)
    at /node_modules/athom-api/dist/index.js:1:1076978
    at new Promise (<anonymous>)
    at new t (/node_modules/athom-api/dist/index.js:1:27558)
    at t.<anonymous> (/node_modules/athom-api/dist/index.js:1:1076948)
    at a (/node_modules/athom-api/dist/index.js:1:324184) {
  name: 'MaxListenersExceededWarning',
  emitter: t {
    _security: { oauth2: [Object] },
    token: {
      name: 'homey_auth',
      isQuery: false,
      value: 'f8bcf243-7814-4cfc-9bbd-fb11319c0f0c:1e1aba4d-0331-4ae4-ad96-30ecce1cdb79:ee6bbcb87d8b7515e3426884902b6b622bd156ec'
    },
    _caches: {
      'HomeyAPI.ManagerDevices.Device': [e],
      'HomeyAPI.ManagerDevices.Capability': [e]
    },
    _pendingCalls: {},
    _baseUrl: 'http://localhost:80',
    _basePath: '/api/manager/devices',
    _eventNS: '/realtime/manager/devices/',
    _eventURI: 'homey:manager:devices',
    authorizationUrl: '',
    managerName: 'ManagerDevices'
  },
  type: 'connect',
  count: 11
}
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect_error listeners added. Use emitter.setMaxListeners() to increase limit
    at d (/node_modules/athom-api/dist/index.js:1:1122279)
    at t.value (/node_modules/athom-api/dist/index.js:1:1125071)
    at t.value (/node_modules/athom-api/dist/index.js:1:1070714)
    at t.value (/node_modules/athom-api/dist/index.js:1:1125140)
    at t.value (/node_modules/athom-api/dist/index.js:1:1125371)
    at /node_modules/athom-api/dist/index.js:1:1076998
    at new Promise (<anonymous>)
    at new t (/node_modules/athom-api/dist/index.js:1:27558)
    at t.<anonymous> (/node_modules/athom-api/dist/index.js:1:1076948)
    at a (/node_modules/athom-api/dist/index.js:1:324184) {
  name: 'MaxListenersExceededWarning',
  emitter: t {
    _security: { oauth2: [Object] },
    token: {
      name: 'homey_auth',
      isQuery: false,
      value: 'f8bcf243-7814-4cfc-9bbd-fb11319c0f0c:1e1aba4d-0331-4ae4-ad96-30ecce1cdb79:ee6bbcb87d8b7515e3426884902b6b622bd156ec'
    },
    _caches: {
      'HomeyAPI.ManagerDevices.Device': [e],
      'HomeyAPI.ManagerDevices.Capability': [e]
    },
    _pendingCalls: {},
    _baseUrl: 'http://localhost:80',
    _basePath: '/api/manager/devices',
    _eventNS: '/realtime/manager/devices/',
    _eventURI: 'homey:manager:devices',
    authorizationUrl: '',
    managerName: 'ManagerDevices'
  },
  type: 'connect_error',
  count: 11
}
× Connection has been lost, exiting...

**Comment by rickardp** [comment]
I can't do anything about these warnings unfortunately, they originate from inside the Homey API and the limits are not accessible from apps. Good thing is, they are only warnings
