### ISSUE TITLE
0.2.7 App doesn't start up correctly if a variable value is 'null'

### ISSUE THREAD

**Issue by ralfvd** [rickardp/homey-prometheus-exporter#23]
If a variable has null as value, the app doesn't start up correctly  ( no open port on 9414 ) . 

It also seems to stop responding when after a succesfull startup , a variable becomes 'null' . 

See output on startup ( I added a console.log (var[varNames]) in app.js:115
{
  __athom_api_type: 'HomeyAPI.ManagerLogic.Variable',
  id: '022d21e7-d115-4017-86a5-9111bc541999',
  name: 'Volume test',
  type: 'number',
  value: null
}
Unhandled Rejection at: Promise {
  <rejected> TypeError: Value is not a valid number: null
      at Object.set (/node_modules/prom-client/lib/gauge.js:222:10)
      at timeCode.name (/app.js:149:50)
      at timeCode (/app.js:441:16)
      at PrometheusApp.updateVariable (/app.js:139:9)
      at /app.js:116:22
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async timeAsyncCode (/app.js:416:16)
      at async PrometheusApp.onInit (/app.js:66:9)
} reason: TypeError: Value is not a valid number: null
    at Object.set (/node_modules/prom-client/lib/gauge.js:222:10)
    at timeCode.name (/app.js:149:50)
    at timeCode (/app.js:441:16)
    at PrometheusApp.updateVariable (/app.js:139:9)
    at /app.js:116:22
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeAsyncCode (/app.js:416:16)
    at async PrometheusApp.onInit (/app.js:66:9)

**Comment by rickardp** [comment]
Thank you for reporting. It seems like something that started appearing in the newer Homey version. Will be fixed in the next version

**Comment by rickardp** [comment]
Test version is out. Can you please go to https://homey.app/a/io.prometheus/test/ and verify that the problem is fixed?
